services:
  app:
    image: golang:1.22
    ports:
      - "8080:8080"
    depends_on:
      - db
    working_dir: /go/src/app
    command: tail -f /dev/null
    environment:
      GIN_MODE: ${GIN_MODE}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_KEY: ${JWT_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DOMAIN: ${DOMAIN}
      CLIENT_ID_GITHUB_AUTH: ${CLIENT_ID_GITHUB_AUTH}
      CLIENT_SECRET_GITHUB_AUTH: ${CLIENT_SECRET_GITHUB_AUTH}
    volumes:
      - ./app:/go/src/app

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data: {}
